# -*- coding: utf-8 -*-
"""Lab_2_fml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sH9f-9kXRjK2B-DzPuRYxeRk6e56RCey
"""

import pandas as pd
import warnings

warnings.filterwarnings("ignore")

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

X = df[["Study_Hours", "Attendance"]]
y = df["Result"]

# Base model
base_tree = DecisionTreeClassifier()

# Bagging classifier
bagging_model = BaggingClassifier(
    estimator=base_tree,
    n_estimators=10,
    bootstrap=True,
    random_state=42
)

# Train model
bagging_model.fit(X, y)

# New student data
new_student = [[3.5, 72]]  # Study hours = 3.5, Attendance = 72%

prediction = bagging_model.predict(new_student)
print("Bagging Prediction:", "Pass" if prediction[0] == 1 else "Fail")

rf_model = RandomForestClassifier(
    n_estimators=10,
    random_state=42
)

# Train Random Forest
rf_model.fit(X, y)

rf_prediction = rf_model.predict(new_student)
print("Random Forest Prediction:", "Pass" if rf_prediction[0] == 1 else "Fail")

